clear;
close all;
clc;
for i = 1 : 7
    if (i ==1)
        tunes = zeros([7 4]);
        tunes(7, 1) = 220;                                                  %f major-> 1 corresponding to f
        tunes(7, 2) = 440;
        tunes(7, 3) = 880;
        frequency_diff = 2^(1/12).^[-10, -9, -7, -5, -4, -2, 0]';           %The semitone frequency multiplier is 2^(1/12)
    end
    tunes(i, 1:end) = tunes(7, 1:end) .* frequency_diff(i);
end
% tunes=%[
% 123   247   494     0
% 131   262   523     0
% 147   294   587     0
% 165   330   659     0
% 175   349   698     0
% 196   392   784     0
% 220   440   880     0
% ]

frequency_sampling = 8000;                                          %sampling frequency
length_of_beat = 0.8;

bass = @(x) x;                                                      %low pitch
alto = @(x) x + 7;                                                  %mid pitch
treble = @(x) x + 14;                                               %high pitch
pause = @(x) 22;

% song = [...
%     pause(0),0.5;...
%     % xiao chuan jing jing wang fan
%     alto(3),0.5;...
%     alto(6),0.5;...
%     treble(3),0.5;...
%     treble(3),0.75;...
%     treble(2),0.25;...
%     treble(4),1;...
%     pause(0),0.5;...
%     % ma di si de hai an
%     alto(3),0.5;...
%     alto(5),0.5;...
%     treble(2),0.5;...
%     treble(2),0.75;...
%     treble(1),0.25;...
%     treble(3),1;...
%     pause(0),0.5;...
%     %xing kong xia de ye wan
%     alto(3),0.5;...
%     alto(6),0.5;...
%     treble(1),0.5;...
%     treble(1),0.75;...
%     alto(7),0.25;...
%     treble(2),1;...
%     pause(0),0.5;...
%     %jiao gei fan gu dian ran
%     alto(3),0.5;...
%     alto(4),0.5;...
%     treble(1),0.5;...
%     treble(1),0.75;...
%     treble(2),0.25;...
%     alto(7),1;...
%     pause(0),0.5
%     %meng mei de tai duan zan
%     alto(3),0.5;...
%     alto(6),0.5;...
%     treble(3),0.5;...
%     treble(3),0.75;...
%     treble(2),0.25;...
%     treble(7),1;...
%     %pause(0),0.5
%     %meng ke qiao shang na han
%     treble(8),0.5;...
%     treble(7),0.5;...
%     treble(3),0.5;...
%     treble(2),0.75;...
%     treble(3),0.25;...
%     treble(1),1;...
%     pause(0),0.5
%     %zhe shi shang de re nao
%     treble(1),0.5;...
%     alto(7),0.5;...
%     treble(1),0.5;...
%     treble(3),0.75;...
%     treble(2),0.25
%     alto(6),1;...
%     pause(0),0.5;...
%     %chu zi gu dan
%     alto(3),0.5;...
%     treble(1),0.5;...
%     alto(7),0.75;...
%     alto(6),2;]

%The pitch of each tone
song_pitch =[...
    pause(0);...
    % xiao chuan jing jing wang fan
    alto(3);...
    alto(6);...
    treble(3);...
    treble(3);...
    treble(2);...
    treble(4);...
    pause(0);...
    % ma di si de hai an
    alto(3);...
    alto(5);...
    treble(2);...
    treble(2);...
    treble(1);...
    treble(3);...
    pause(0);...
    %xing kong xia de ye wan
    alto(3);...
    alto(6);...
    treble(1);...
    treble(1);...
    alto(7);...
    treble(2);...
    pause(0);...
    %jiao gei fan gu dian ran
    alto(3);...
    alto(4);...
    treble(1);...
    treble(1);...
    treble(2);...
    alto(7);...
    pause(0);...
    %meng mei de tai duan zan
    alto(3);...
    alto(6);...
    treble(3);...
    treble(3);...
    treble(2);...
    treble(7);...
    %meng ke qiao shang na han
    treble(8);...
    treble(7);...
    treble(3);...
    treble(2);...
    treble(3);...
    treble(1);...
    pause(0);...
    %zhe shi shang de re nao
    treble(1);...
    alto(7);...
    treble(1);...
    treble(3);...
    treble(2);...
    alto(6);...
    pause(0);...
    %chu zi gu dan
    alto(3);...
    treble(1);...
    alto(7);...
    alto(6)];
%The length of each tone
song_length =[...
    0.5;...
    % xiao chuan jing jing wang fan
    0.5;...
    0.5;...
    0.5;...
    0.75;...
    0.25;...
    1;...
    0.5;...
    % ma di si de hai an
    0.5;...
    0.5;...
    0.5;...
    0.75;...
    0.25;...
    1;...
    0.5;...
    %xing kong xia de ye wan
    0.5;...
    0.5;...
    0.5;...
    0.75;...
    0.25;...
    1;...
    0.5;...
    %jiao gei fan gu dian ran
    0.5;...
    0.5;...
    0.5;...
    0.75;...
    0.25;...
    1;...
    0.5;...
    %meng mei de tai duan zan
    0.5;...
    0.5;...
    0.5;...
    0.75;...
    0.25;...
    1.5;...
    %meng ke qiao shang na han
    0.5;...
    0.5;...
    0.5;...
    0.75;...
    0.25;...
    1;...
    0.5;...
    %zhe shi shang de re nao
    0.5;...
    0.5;...
    0.5;...
    0.75;...
    0.25;...
    1;...
    0.5;...
    %chu zi gu dan
    0.5;...
    0.5;...
    0.75;...
    2];

tone_sampling = [];
padding = 1;
last_padding = 0;
for i = 1 : 1 : length(song_length)
    f = tunes(song_pitch(i));                                                               %The pitch of each tone
    length_of_each_tone = song_length(i) * length_of_beat;                                  %The length of each tone
    length_of_each_tone_padding = frequency_sampling * length_of_each_tone * padding;
    t = linspace(0, length_of_each_tone * padding - 1 / frequency_sampling, length_of_each_tone_padding)';
    tone_sampling_temp = my_envelope(t/length_of_each_tone) .* (sin(2 * pi * f * t) + 0.2 * sin(2 * pi * 2 * f * t) + 0.1 * sin(2 * pi * 3 * f * t)+0.4 * sin(2 * pi * 4 * f * t));         %These sounds are represented by a sinusoidal signal with an amplitude of 1 and sampling frequency of 8kHz(after padding)[The fundamental wave amplitude is 1, the second harmonic amplitude is 0:2, the third harmonic amplitude is 0:3]
    if (last_padding == 0)
        tone_sampling = [tone_sampling; tone_sampling_temp];
    else
        tone_sampling = [tone_sampling(1:end-last_padding); tone_sampling(end-last_padding)+tone_sampling_temp(1:last_padding); tone_sampling_temp(last_padding+1:end)];
    end
    last_padding = round(length_of_each_tone_padding - frequency_sampling * length_of_each_tone);
end

subplot(3,1,1);                                                     %draw envelope functiofn
fplot(@(t) my_envelope(t), [-padding+1, padding * 1.1]);
title("envelope function");
subplot(3,1,2);
plot([0 : 5000 - 1] / frequency_sampling, tone_sampling(1 : 5000));
title("sound waveform");
subplot(3,1,3);
plot([0 : length(tone_sampling) - 1] / frequency_sampling, tone_sampling);
title("sound waveform");

sound(tone_sampling, frequency_sampling);                       %play sampled tones
audiowrite('music_05.wav', tone_sampling, frequency_sampling);  %store .wav

function [y, z] = my_envelope(x)
    z = 1;
    y = (x >= 0 & x < 0.1) .* ( (-1./(0.1.^2)).* (x-0.1).^2+ 1) + (x >= 0.1 & x < 1.5) .* ((((1 + (1.5-0.1)./(0.1-1))-1)./(1.5-0.1).^2) .* (x -0.1).^2 + 1) + (x >= 1.5 & x < 1) .* ((1.5-0.1)./(1.5-1) .*(((1 + (1.5-0.1)./(0.1-1))-1)./(1.5-0.1).^2)) .* (x -1).^2;
end